Sprite 1
Melittlecrazy/SCP-fight-club pull request #2
Opened 2020-10-07 03:04 UTC by Melittlecrazy

Added the basic features of moving and jumping.

2020-10-08 21:20 UTC, Sebp23 commented on SCP fight club/Assets/Scripts/Movement.cs
> +            if (Input.GetKeyDown(KeyCode.Space))
Too much of an indent

2020-10-08 21:33 UTC, Sebp23 requested changes
Requesting some small style edits and some access modifier edits.

2020-10-08 21:33 UTC, Sebp23 commented on SCP fight club/Assets/Scripts/Movement.cs
> +    public float speed = 1.0f;
I recommend making the speed float private and using [SerializeField]

2020-10-08 21:33 UTC, Sebp23 commented on SCP fight club/Assets/Scripts/Movement.cs
> +         if(Input.GetKey(KeyCode.RightArrow))
I think there's a space on this line before the start of the if statement. Might wanna get rid of that for style rules.

2020-10-08 21:33 UTC, Sebp23 commented on SCP fight club/Assets/Scripts/Movement.cs
> +            if (Input.GetKeyDown(KeyCode.Space))
Too much of an indent here.

2020-10-08 21:33 UTC, Sebp23 commented on SCP fight club/Assets/Scripts/Movement.cs
> +            float jumpVelocity = 10f;
Might want to declare this variable with accelForce and speed since it might become relevant outside this conditional later in the project.

2020-10-08 21:56 UTC, Sebp23 approved these changes

2020-10-08 21:56 UTC, merged

2020-10-15 21:08 UTC, dantogno commented
@Sebp23 Great job reviewing, thanks!